from __future__ import annotations

from typing import cast, TYPE_CHECKING
import pytest
import asyncio

if TYPE_CHECKING:
    from reddit_adapter import Gallery, Post

from .. import media_handler


@pytest.mark.asyncio
async def test_get_streamable_mp4_url():
    urls = ["https://streamable.com/2eyw5n", "http://streamable.com/9o626v"]

    mp4_urls = await asyncio.gather(*map(media_handler.get_streamable_mp4_url, urls))
    for url in mp4_urls:
        assert url and url.split("?")[0].endswith(".mp4")


@pytest.mark.asyncio
async def test_gallery():
    gallery_post: Post = {  # type: ignore
        "kind": "t3",
        "approved_at_utc": None,
        "subreddit": "comics",
        "selftext": "",
        "author_fullname": "t2_8xos045t",
        "saved": False,
        "mod_reason_title": None,
        "gilded": 0,
        "clicked": False,
        "is_gallery": True,
        "title": "Genie",
        "link_flair_richtext": [],
        "subreddit_name_prefixed": "r/comics",
        "hidden": False,
        "pwls": 6,
        "link_flair_css_class": None,
        "downs": 0,
        "thumbnail_height": 140,
        "top_awarded_type": None,
        "hide_score": False,
        "media_metadata": {
            "x8or3pvjiua81": {
                "status": "valid",
                "e": "Image",
                "m": "image/jpg",
                "p": [
                    {
                        "y": 108,
                        "x": 108,
                        "u": "https://preview.redd.it/x8or3pvjiua81.jpg?width=108&crop=smart&auto=webp&s=5e5945b3beaedef70bb9af57c297abe8b95529ba",
                    },
                    {
                        "y": 216,
                        "x": 216,
                        "u": "https://preview.redd.it/x8or3pvjiua81.jpg?width=216&crop=smart&auto=webp&s=395a964856a37954b90379b2f84498bf7f36ebf3",
                    },
                    {
                        "y": 320,
                        "x": 320,
                        "u": "https://preview.redd.it/x8or3pvjiua81.jpg?width=320&crop=smart&auto=webp&s=6efb6422b05c024f7aa3f27326ca140a708605da",
                    },
                    {
                        "y": 640,
                        "x": 640,
                        "u": "https://preview.redd.it/x8or3pvjiua81.jpg?width=640&crop=smart&auto=webp&s=730025cfa3c9b7a895d775691dc29eb20fc55451",
                    },
                ],
                "s": {
                    "y": 800,
                    "x": 800,
                    "u": "https://preview.redd.it/x8or3pvjiua81.jpg?width=800&format=pjpg&auto=webp&s=69de14211f60f9570a8ffa2c2183ba224344f6ad",
                },
                "id": "x8or3pvjiua81",
            },
            "mwqoyovjiua81": {
                "status": "valid",
                "e": "Image",
                "m": "image/jpg",
                "p": [
                    {
                        "y": 108,
                        "x": 108,
                        "u": "https://preview.redd.it/mwqoyovjiua81.jpg?width=108&crop=smart&auto=webp&s=aaae14749947465441cf76c68707a4ab76e68b13",
                    },
                    {
                        "y": 216,
                        "x": 216,
                        "u": "https://preview.redd.it/mwqoyovjiua81.jpg?width=216&crop=smart&auto=webp&s=e4a0aba82447127b0f835407334c691c68032452",
                    },
                    {
                        "y": 320,
                        "x": 320,
                        "u": "https://preview.redd.it/mwqoyovjiua81.jpg?width=320&crop=smart&auto=webp&s=a738dea7687e0f9587d8b87509a2b3b9c73b0baf",
                    },
                    {
                        "y": 640,
                        "x": 640,
                        "u": "https://preview.redd.it/mwqoyovjiua81.jpg?width=640&crop=smart&auto=webp&s=961796b8c69823864843b5564af0e5b584eb0ecd",
                    },
                ],
                "s": {
                    "y": 800,
                    "x": 800,
                    "u": "https://preview.redd.it/mwqoyovjiua81.jpg?width=800&format=pjpg&auto=webp&s=b829a1d3ccf6ed30437d691390973140e0cdf55d",
                },
                "id": "mwqoyovjiua81",
            },
            "2b5c8rvjiua81": {
                "status": "valid",
                "e": "Image",
                "m": "image/jpg",
                "p": [
                    {
                        "y": 108,
                        "x": 108,
                        "u": "https://preview.redd.it/2b5c8rvjiua81.jpg?width=108&crop=smart&auto=webp&s=e01301baf2851068081701e56cf7dd7ea82cc0e7",
                    },
                    {
                        "y": 216,
                        "x": 216,
                        "u": "https://preview.redd.it/2b5c8rvjiua81.jpg?width=216&crop=smart&auto=webp&s=002579b9550f37567ff8503ca0d92b0ffe5a7358",
                    },
                    {
                        "y": 320,
                        "x": 320,
                        "u": "https://preview.redd.it/2b5c8rvjiua81.jpg?width=320&crop=smart&auto=webp&s=2e5f5142c366d8ad53f166da8eab4f6612e139e9",
                    },
                    {
                        "y": 640,
                        "x": 640,
                        "u": "https://preview.redd.it/2b5c8rvjiua81.jpg?width=640&crop=smart&auto=webp&s=4eed4d1647aaf9f958e0250f56a0cae6561ed2ab",
                    },
                ],
                "s": {
                    "y": 800,
                    "x": 800,
                    "u": "https://preview.redd.it/2b5c8rvjiua81.jpg?width=800&format=pjpg&auto=webp&s=f5d7332c4c8a1a0fcc436bf977c37c0555a53c07",
                },
                "id": "2b5c8rvjiua81",
            },
            "mv3giovjiua81": {
                "status": "valid",
                "e": "Image",
                "m": "image/jpg",
                "p": [
                    {
                        "y": 108,
                        "x": 108,
                        "u": "https://preview.redd.it/mv3giovjiua81.jpg?width=108&crop=smart&auto=webp&s=a898e660ad24b80f524486be2ca2506ec2e6796a",
                    },
                    {
                        "y": 216,
                        "x": 216,
                        "u": "https://preview.redd.it/mv3giovjiua81.jpg?width=216&crop=smart&auto=webp&s=279de5ec1617c97900b8adc855ff03bffcf4bf2b",
                    },
                    {
                        "y": 320,
                        "x": 320,
                        "u": "https://preview.redd.it/mv3giovjiua81.jpg?width=320&crop=smart&auto=webp&s=250b3aba0cc1f691fa8acf093839618735851795",
                    },
                    {
                        "y": 640,
                        "x": 640,
                        "u": "https://preview.redd.it/mv3giovjiua81.jpg?width=640&crop=smart&auto=webp&s=8bcbb161f36d2cdae9c1d65d208993607d1243a9",
                    },
                ],
                "s": {
                    "y": 800,
                    "x": 800,
                    "u": "https://preview.redd.it/mv3giovjiua81.jpg?width=800&format=pjpg&auto=webp&s=991cf2b6e1400404eacc9c01a2a6f075d172ca10",
                },
                "id": "mv3giovjiua81",
            },
            "y80e83wjiua81": {
                "status": "valid",
                "e": "Image",
                "m": "image/jpg",
                "p": [
                    {
                        "y": 108,
                        "x": 108,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=108&crop=smart&auto=webp&s=d65a9697e86f5947c8fa50dfba362cd84010d59c",
                    },
                    {
                        "y": 216,
                        "x": 216,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=216&crop=smart&auto=webp&s=e72ad0b1dd46afc2b800d68b37b9a3759d88ed3f",
                    },
                    {
                        "y": 320,
                        "x": 320,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=320&crop=smart&auto=webp&s=860ff92ad5e99d7ea73db8811b87bd9fa323710f",
                    },
                    {
                        "y": 640,
                        "x": 640,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=640&crop=smart&auto=webp&s=f9877b53db9dc64a8b6b3c7e725483d7282d07c6",
                    },
                    {
                        "y": 960,
                        "x": 960,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=960&crop=smart&auto=webp&s=8bee0d5745d4fa78c6fa3ca45bc0ba2cf314c81c",
                    },
                    {
                        "y": 1080,
                        "x": 1080,
                        "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=1080&crop=smart&auto=webp&s=73d0cf1e99f1d96ce3ad5fe6449e8a309ca2dae7",
                    },
                ],
                "s": {
                    "y": 1440,
                    "x": 1440,
                    "u": "https://preview.redd.it/y80e83wjiua81.jpg?width=1440&format=pjpg&auto=webp&s=77447641333d258ba92cf493a42da72b885f3d90",
                },
                "id": "y80e83wjiua81",
            },
        },
        "name": "t3_s0hxfc",
        "quarantine": False,
        "link_flair_text_color": "dark",
        "upvote_ratio": 0.88,
        "author_flair_background_color": None,
        "ups": 42662,
        "domain": "reddit.com",
        "media_embed": {},
        "thumbnail_width": 140,
        "author_flair_template_id": None,
        "is_original_content": False,
        "user_reports": [],
        "secure_media": None,
        "is_reddit_media_domain": False,
        "is_meta": False,
        "category": None,
        "secure_media_embed": {},
        "gallery_data": {
            "items": [
                {"media_id": "mv3giovjiua81", "id": 101071881},
                {"media_id": "mwqoyovjiua81", "id": 101071882},
                {"media_id": "x8or3pvjiua81", "id": 101071883},
                {"media_id": "2b5c8rvjiua81", "id": 101071884},
                {"media_id": "y80e83wjiua81", "id": 101071885},
            ]
        },
        "link_flair_text": None,
        "can_mod_post": False,
        "score": 42662,
        "approved_by": None,
        "is_created_from_ads_ui": False,
        "author_premium": True,
        "thumbnail": "https://a.thumbs.redditmedia.com/_pubDNQrwDpRCbTfpIBIovwlGgimTqDjl53MUCoBoY4.jpg",
        "edited": False,
        "author_flair_css_class": None,
        "author_flair_richtext": [],
        "gildings": {"gid_1": 15},
        "content_categories": ["comics"],
        "is_self": False,
        "subreddit_type": "public",
        "created": 1641814064.0,
        "link_flair_type": "text",
        "wls": 6,
        "removed_by_category": None,
        "banned_by": None,
        "author_flair_type": "text",
        "total_awards_received": 43,
        "allow_live_comments": True,
        "selftext_html": None,
        "likes": None,
        "suggested_sort": None,
        "banned_at_utc": None,
        "url_overridden_by_dest": "https://www.reddit.com/gallery/s0hxfc",
        "view_count": None,
        "archived": False,
        "no_follow": False,
        "is_crosspostable": False,
        "pinned": False,
        "over_18": False,
        "all_awardings": [
            {
                "giver_coin_reward": 0,
                "subreddit_id": None,
                "is_new": False,
                "days_of_drip_extension": 0,
                "coin_price": 100,
                "id": "award_b4072731-c0fb-4440-adc7-1063d6a5e6a0",
                "penny_donate": 0,
                "award_sub_type": "GLOBAL",
                "coin_reward": 0,
                "icon_url": "https://i.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png",
                "days_of_premium": 0,
                "tiers_by_required_awardings": None,
                "resized_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=16&height=16&auto=webp&s=8e644eb9ffccee5f11d72e759883a6c825f7d89e",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=32&height=32&auto=webp&s=c49ad07c88610c7efe98a54453d9ce5ddf887a1d",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=48&height=48&auto=webp&s=80eb767a877a78c181af1385c2ed98f067b38092",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=64&height=64&auto=webp&s=b2b65ceeff9933f5e70387893e661b7e9f1f1556",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=128&height=128&auto=webp&s=aec3cf53a1aeabe4c2ecc4ad83b2d0f2993d1afd",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_width": 2048,
                "static_icon_width": 2048,
                "start_date": None,
                "is_enabled": True,
                "awardings_required_to_grant_benefits": None,
                "description": "C'est magnifique",
                "end_date": None,
                "subreddit_coin_reward": 0,
                "count": 1,
                "static_icon_height": 2048,
                "name": "Masterpiece",
                "resized_static_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=16&height=16&auto=webp&s=8e644eb9ffccee5f11d72e759883a6c825f7d89e",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=32&height=32&auto=webp&s=c49ad07c88610c7efe98a54453d9ce5ddf887a1d",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=48&height=48&auto=webp&s=80eb767a877a78c181af1385c2ed98f067b38092",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=64&height=64&auto=webp&s=b2b65ceeff9933f5e70387893e661b7e9f1f1556",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=128&height=128&auto=webp&s=aec3cf53a1aeabe4c2ecc4ad83b2d0f2993d1afd",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_format": "PNG",
                "icon_height": 2048,
                "penny_price": 0,
                "award_type": "global",
                "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png",
            },
            {
                "giver_coin_reward": None,
                "subreddit_id": None,
                "is_new": False,
                "days_of_drip_extension": 0,
                "coin_price": 300,
                "id": "award_28e8196b-d4e9-45bc-b612-cd4c7d3ed4b3",
                "penny_donate": None,
                "award_sub_type": "GLOBAL",
                "coin_reward": 0,
                "icon_url": "https://i.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png",
                "days_of_premium": 0,
                "tiers_by_required_awardings": None,
                "resized_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png?width=16&height=16&auto=webp&s=9d714b25ca25d05e3310bc60bc1714ddf7951331",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png?width=32&height=32&auto=webp&s=d584b15c8e17d61fa8ae319a91d351c8fe35b918",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png?width=48&height=48&auto=webp&s=d9fb2c025611a15e6bb4437734f92db99b93fd12",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png?width=64&height=64&auto=webp&s=744fb200d76bf21f6e023ba98d3b4189b34973e3",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/35d17tf5e5f61_oldrocketlike.png?width=128&height=128&auto=webp&s=c180572afbc080622a8ac8441c3bc5214597d05a",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_width": 2048,
                "static_icon_width": 2048,
                "start_date": None,
                "is_enabled": True,
                "awardings_required_to_grant_benefits": None,
                "description": "When an upvote just isn't enough, smash the Rocket Like.",
                "end_date": None,
                "subreddit_coin_reward": 0,
                "count": 1,
                "static_icon_height": 2048,
                "name": "Rocket Like",
                "resized_static_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png?width=16&height=16&auto=webp&s=24fc4d912e595c3fed2ce0deef1c13f70df56056",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png?width=32&height=32&auto=webp&s=f9d869602e0d8b719186cc603864a42699e5c96e",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png?width=48&height=48&auto=webp&s=b223ac8fdd206b683b840c2782307c3f01b04fb7",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png?width=64&height=64&auto=webp&s=a0b840c6ecdee904012a6c53c40194733b72bca8",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png?width=128&height=128&auto=webp&s=b2e2ca67e067f82ff9b4ea1fe1b39395ca622894",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_format": None,
                "icon_height": 2048,
                "penny_price": None,
                "award_type": "global",
                "static_icon_url": "https://i.redd.it/award_images/t5_q0gj4/9fmmyy3c68361_RocketLikeSanta.png",
            },
            {
                "giver_coin_reward": None,
                "subreddit_id": None,
                "is_new": False,
                "days_of_drip_extension": 0,
                "coin_price": 100,
                "id": "gid_1",
                "penny_donate": None,
                "award_sub_type": "GLOBAL",
                "coin_reward": 0,
                "icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
                "days_of_premium": 0,
                "tiers_by_required_awardings": None,
                "resized_icons": [
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_width": 512,
                "static_icon_width": 512,
                "start_date": None,
                "is_enabled": True,
                "awardings_required_to_grant_benefits": None,
                "description": "Shows the Silver Award... and that's it.",
                "end_date": None,
                "subreddit_coin_reward": 0,
                "count": 15,
                "static_icon_height": 512,
                "name": "Silver",
                "resized_static_icons": [
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_format": None,
                "icon_height": 512,
                "penny_price": None,
                "award_type": "global",
                "static_icon_url": "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
            },
            {
                "giver_coin_reward": None,
                "subreddit_id": None,
                "is_new": False,
                "days_of_drip_extension": 0,
                "coin_price": 150,
                "id": "award_f44611f1-b89e-46dc-97fe-892280b13b82",
                "penny_donate": None,
                "award_sub_type": "GLOBAL",
                "coin_reward": 0,
                "icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
                "days_of_premium": 0,
                "tiers_by_required_awardings": None,
                "resized_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&height=16&auto=webp&s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&height=32&auto=webp&s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&height=48&auto=webp&s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&height=64&auto=webp&s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&height=128&auto=webp&s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_width": 2048,
                "static_icon_width": 2048,
                "start_date": None,
                "is_enabled": True,
                "awardings_required_to_grant_benefits": None,
                "description": "Thank you stranger. Shows the award.",
                "end_date": None,
                "subreddit_coin_reward": 0,
                "count": 15,
                "static_icon_height": 2048,
                "name": "Helpful",
                "resized_static_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=16&height=16&auto=webp&s=a5662dfbdb402bf67866c050aa76c31c147c2f45",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=32&height=32&auto=webp&s=a6882eb3f380e8e88009789f4d0072e17b8c59f1",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=48&height=48&auto=webp&s=e50064b090879e8a0b55e433f6ee61d5cb5fbe1d",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=64&height=64&auto=webp&s=8e5bb2e76683cb6b161830bcdd9642049d6adc11",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png?width=128&height=128&auto=webp&s=eda4a9246f95f42ee6940cc0ec65306fd20de878",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_format": None,
                "icon_height": 2048,
                "penny_price": None,
                "award_type": "global",
                "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/klvxk1wggfd41_Helpful.png",
            },
            {
                "giver_coin_reward": None,
                "subreddit_id": None,
                "is_new": False,
                "days_of_drip_extension": 0,
                "coin_price": 125,
                "id": "award_5f123e3d-4f48-42f4-9c11-e98b566d5897",
                "penny_donate": None,
                "award_sub_type": "GLOBAL",
                "coin_reward": 0,
                "icon_url": "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
                "days_of_premium": 0,
                "tiers_by_required_awardings": None,
                "resized_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&height=16&auto=webp&s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&height=32&auto=webp&s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&height=48&auto=webp&s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&height=64&auto=webp&s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&height=128&auto=webp&s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_width": 2048,
                "static_icon_width": 2048,
                "start_date": None,
                "is_enabled": True,
                "awardings_required_to_grant_benefits": None,
                "description": "When you come across a feel-good thing.",
                "end_date": None,
                "subreddit_coin_reward": 0,
                "count": 11,
                "static_icon_height": 2048,
                "name": "Wholesome",
                "resized_static_icons": [
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=16&height=16&auto=webp&s=92932f465d58e4c16b12b6eac4ca07d27e3d11c0",
                        "width": 16,
                        "height": 16,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=32&height=32&auto=webp&s=d11484a208d68a318bf9d4fcf371171a1cb6a7ef",
                        "width": 32,
                        "height": 32,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=48&height=48&auto=webp&s=febdf28b6f39f7da7eb1365325b85e0bb49a9f63",
                        "width": 48,
                        "height": 48,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=64&height=64&auto=webp&s=b4406a2d88bf86fa3dc8a45aacf7e0c7bdccc4fb",
                        "width": 64,
                        "height": 64,
                    },
                    {
                        "url": "https://preview.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png?width=128&height=128&auto=webp&s=19555b13e3e196b62eeb9160d1ac1d1b372dcb0b",
                        "width": 128,
                        "height": 128,
                    },
                ],
                "icon_format": None,
                "icon_height": 2048,
                "penny_price": None,
                "award_type": "global",
                "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/5izbv4fn0md41_Wholesome.png",
            },
        ],
        "awarders": [],
        "media_only": False,
        "can_gild": False,
        "spoiler": False,
        "locked": False,
        "author_flair_text": None,
        "treatment_tags": [],
        "visited": False,
        "removed_by": None,
        "mod_note": None,
        "distinguished": None,
        "subreddit_id": "t5_2qh0s",
        "author_is_blocked": False,
        "mod_reason_by": None,
        "num_reports": None,
        "removal_reason": None,
        "link_flair_background_color": "",
        "id": "s0hxfc",
        "is_robot_indexable": True,
        "report_reasons": None,
        "author": "Sychomic",
        "discussion_type": None,
        "num_comments": 594,
        "send_replies": True,
        "whitelist_status": "all_ads",
        "contest_mode": False,
        "mod_reports": [],
        "author_patreon_flair": False,
        "author_flair_text_color": None,
        "permalink": "/r/comics/comments/s0hxfc/genie/",
        "parent_whitelist_status": "all_ads",
        "stickied": False,
        "url": "https://www.reddit.com/gallery/s0hxfc",
        "subreddit_subscribers": 1715662,
        "created_utc": 1641814064.0,
        "num_crossposts": 8,
        "media": None,
        "is_video": False,
    }

    assert media_handler.is_gallery(gallery_post)
    gallery: Gallery = gallery_post  # type: ignore
    assert media_handler.get_gallery_image_urls(gallery) == [
        "https://preview.redd.it/mv3giovjiua81.jpg?width=800&format=pjpg&auto=webp&s=991cf2b6e1400404eacc9c01a2a6f075d172ca10",
        "https://preview.redd.it/mwqoyovjiua81.jpg?width=800&format=pjpg&auto=webp&s=b829a1d3ccf6ed30437d691390973140e0cdf55d",
        "https://preview.redd.it/x8or3pvjiua81.jpg?width=800&format=pjpg&auto=webp&s=69de14211f60f9570a8ffa2c2183ba224344f6ad",
        "https://preview.redd.it/2b5c8rvjiua81.jpg?width=800&format=pjpg&auto=webp&s=f5d7332c4c8a1a0fcc436bf977c37c0555a53c07",
        "https://preview.redd.it/y80e83wjiua81.jpg?width=1440&format=pjpg&auto=webp&s=77447641333d258ba92cf493a42da72b885f3d90",
    ]
